frase = "Mangericão Com Salada"
print (len(frase))




print ('''sb dkvasvdfs,vhdfs v,ds md\n vm,d vsd bd bsd vfsdbvmdsvg 
efvefsvefvevbegbrsebrwbrswbrsbrstwbwrbwrtbgrwtbrwsbtrwbrtrwbtrbwrdf
gkeglthbrwhkgvbhretbkgrkhvtrejvbgrvhbgrkehgbvbtrkvhrwvbghjrtbvhjrtbvjrvgf
rrlhrhgrtlehrlehgrkhbgrelgrkejlgbkjerlgkrtljgrelhgkrtluklyegfinallydfb gf
fvhwkvjtlgvvbj,hv,vbhjfrhjmvremrjhmbvtrjhvbwrjvbhmfvbhumnfrvbmfrvhjrmvbjtrmvbrmvfgbbdf
wvbrwhvulrwhvlrwvhliurvhrwkigvkvruvhjrtvjlksvhrlkjbvhrbjkgrbkjrlubrigburkiubgkiurkiurnhkiugrbb dfg''')